---
  device: cuda:1
  total_training_steps: 1500
  CellLineTransferLearner:
    direct_only: False
    ContrastiveLearner:
      CellLineEncoder:
        input_dim: 7751
        output_dim: 512
        hidden_layers: []
        skip_levels: [-1, -1, -1]
        activation: relu
        virtual_batch_size: 32
        dropout: 0.05
      PDXEncoder:
        input_dim: 7751
        output_dim: 512
        hidden_layers: []
        skip_levels: [-1, -1, -1]
        activation: relu
        virtual_batch_size: 32
        dropout: 0.05
      ContrastiveProjection:
        input_dim: 128
        output_dim: 128
        hidden_layers: []
        activation: gelu
        virtual_batch_size: 32
        dropout: 0.0
      temperature: 0.07
    CellLineResponsePredictor:
      input_dim: -1
      output_dim: 1
      hidden_layers: [32]
      activation: relu
      virtual_batch_size: 32
      dropout: 0.05
    DirectPredictor:
      input_dim: -1
      output_dim: 1
      hidden_layers: [512, 256]
      activation: relu
      virtual_batch_size: 32
      dropout: 0.05
      sparse: False
    DirectPDXPredictor:
      DirectPredictor:
        input_dim: -1
        output_dim: 1
        hidden_layers: [512, 256]
        activation: relu
        virtual_batch_size: 32
        dropout: 0.05
        sparse: False
    LGBMCellLineResponseRegressor:
      learning_rate: 0.01
      n_estimators: 100
      num_leaves: 31
      min_split_gain: 0
      reg_alpha: 0
      reg_lambda: 0
      device: cuda:7
